model_name: "DeepseekV3LPR-0.6B-0.1b"

model_type: "DeepseekV3LPR"

eval: true

model_config:
  vocab_size: 151936
  hidden_size: 1024
  qk_rope_head_dim: 64
  v_head_dim: 128
  qk_nope_head_dim: 128
  intermediate_size: 1408
  moe_intermediate_size: 110
  num_hidden_layers: 6
  num_attention_heads: 8
  num_key_value_heads: 8
  n_routed_experts: 128
  num_experts_per_tok: 8
  norm_topk_prob: True
  n_group: 8
  topk_group: 6
  hidden_act: "silu"
  max_position_embeddings: 4096
  initializer_range: 0.02
  rms_norm_eps: 1.0e-6
  n_shared_experts: 5
  router_aux_loss_coef: 0.0
  output_router_kl: true
  router_kl_loss_coef: 0.01
  router_latent_dim: 16
  router_ema_decay: 0.8
  diversity_lambda: 1.0
  output_router_logit: true
  output_router_logits:
  first_k_dense_replace: 0
  diversity_type: "orthogonal"
  SimilarityMetrics: "VectorSimilarity"
  routing_metrics: "Cosine"
  kl_weight: 0.01
  align_weight: 0.05
  div_weight: 1.0
  unit_ball: false

training_config:
  total_steps: 4000
  warmup_ratio: 0.05
  stable_ratio: 0.75
  max_length: 1024
  adam_beta1: 0.9
  adam_beta2: 0.95
  weight_decay: 0.1
  lr: 0.001
  min_lr_ratio: 0.05
  gradient_clip_norm: 1.0
  gradient_accumulate_steps: 18
  per_device_train_batch_size: 15
  per_device_eval_batch_size: 20
